// Промисы: сравните then и catch

promise.then(f1).catch(f2);

promise.then(f1, f2);

// Нет разные, в первом случае ошибка будет отработана в catch, а во втором нет